namespace AdventOfCode2024;

internal static class Program
{
    private static string[] TestInput => 
        """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
        """
            .Split("\n");

    private static string[] _realInput = InputLoader.Load(8, separator: "\n");

    private static void Main(string[] args)
    {
        Day8.Part1(_realInput);
        Day8.Part2(TestInput); 
    }
}